Repository nidhaloff/deep-translator, pull requests merged in 2023-06, with the labels that each got.

#217 Added a list of languages supported by MyMemory
  deep_translator/constants.py
  deep_translator/mymemory.py
  tests/test_mymemory.py
Labels: enhancement, fix

#219 added baidu support
  deep_translator/__init__.py
  deep_translator/baidu.py
  deep_translator/constants.py
  deep_translator/exceptions.py
  docs/README.rst
  tests/test_baidu.py
Labels: enhancement, pending

#220 Hotfix/digit translation
  deep_translator/deepl.py
  deep_translator/google.py
  deep_translator/libre.py
  deep_translator/linguee.py
  deep_translator/mymemory.py
  deep_translator/papago.py
  deep_translator/pons.py
  deep_translator/qcri.py
  deep_translator/validate.py
  deep_translator/yandex.py
  tests/test_google.py
  tests/test_libre.py
  tests/test_linguee.py
  tests/test_mymemory.py
  tests/test_pons.py
Labels: bug, fix
